version = 0.1
[default.deploy.parameters]
stack_name = "api-spec-ind"
resolve_s3 = true
s3_prefix = "api-spec-ind"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
